In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [13]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do',
    'smile face',
    'I hate you',
    'Happy new year'
]

In [14]:
cv = CountVectorizer()

### 사전을 만들어라.!! => fit()
### 사전에 들어있는 id로 인코딩을 해라.!! => tranfrom()
### 1,2을 함께 처리하고자 하는 경우는 => fit_transform()

In [15]:
cv.fit_transform(corpus)

<6x15 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [16]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

### fit --> transform

In [29]:
tfidf = TfidfVectorizer()

In [30]:
tfidf = tfidf.fit(corpus)

In [31]:
tfidf.transform(corpus)

<6x15 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [32]:
tfidf.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.47249269,
        0.        , 0.47249269, 0.        , 0.        , 0.        ,
        0.47249269, 0.        , 0.        , 0.32711256, 0.47249269],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.82219037, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.56921261, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027, 0.        , 0.        , 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.82219037, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 

In [33]:
sentence  = ["i like like like hate smile"]

In [34]:
nd2array = cv.transform(sentence).toarray()
nd2array

array([[0, 0, 0, 1, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [35]:
nd2array[0]

array([0, 0, 0, 1, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [36]:
nd2array2 = tfidf.transform(sentence).toarray()
nd2array2

array([[0.        , 0.        , 0.        , 0.30151134, 0.        ,
        0.90453403, 0.        , 0.        , 0.        , 0.30151134,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [37]:
cv.inverse_transform(nd2array)

[array(['hate', 'like', 'smile'], dtype='<U6')]

In [38]:
tfidf.inverse_transform(nd2array2)

[array(['hate', 'like', 'smile'], dtype='<U6')]

In [53]:
voc_list = cv.vocabulary_
voc_list

{'you': 13,
 'know': 4,
 'want': 10,
 'your': 14,
 'love': 6,
 'like': 5,
 'what': 11,
 'should': 8,
 'do': 0,
 'smile': 9,
 'face': 1,
 'hate': 3,
 'happy': 2,
 'new': 7,
 'year': 12}

In [46]:
feature_list = cv.get_feature_names() # 사전에 무었이 들어있는지
feature_list

['do',
 'face',
 'happy',
 'hate',
 'know',
 'like',
 'love',
 'new',
 'should',
 'smile',
 'want',
 'what',
 'year',
 'you',
 'your']

In [45]:
# dic <--- list

In [48]:
dictionary = dict()

In [56]:
for idnex, element in enumerate(feature_list):
    dictionary[idnex] = element
dictionary

{0: 'do',
 1: 'face',
 2: 'happy',
 3: 'hate',
 4: 'know',
 5: 'like',
 6: 'love',
 7: 'new',
 8: 'should',
 9: 'smile',
 10: 'want',
 11: 'what',
 12: 'year',
 13: 'you',
 14: 'your'}

In [59]:
### 스팸을 나타내는 사전을 만들어주세요.(10개)
### 스팸이 아닌 사전을 만들어주세요.(10개)

In [58]:
## 광고!! 짱 좋은 판매 홍보전략입니다.!! => 스팸입니다.!!

In [85]:
li_spam = ['advertise','promotion','sales','sign','member','lucky','present','raffle','hero','special']
li_nspam = ['confirm','order','check','customer','payment','delivery','normal','club']

In [80]:
dic_spam = dict()
dic_nspam = dict()

In [89]:
spam_cv_fit = cv.fit(li_spam)

In [90]:
email = ["promotion !! this is a great sales promotion strategy..!!"]

In [91]:
email_spam_array = spam_cv_fit.transform(email).toarray()
email_spam_array

array([[0, 0, 0, 0, 0, 2, 0, 1, 0, 0]], dtype=int64)

In [93]:
nspam_cv_fit = cv.fit(li_nspam)

In [94]:
email_nspam_array = nspam_cv_fit.transform(email).toarray()
email_nspam_array

array([[0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [141]:
li_spam = ['광고','특가','판매','가입','회원','행운','선물','홍보']
li_nspam = ['승인','주문','확인','고객','지불','배송','일반','동호회']

In [142]:
email = ["광고!! 특가 입니다 !! 지금 가입 하시는 고객 분께 좋은 판매 빠른 배송 보장 합니다.!!"]

In [143]:
spam_cv_fit = cv.fit(li_spam)

In [144]:
result1 = spam_cv_fit.transform(email).toarray()
result1

array([[1, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [145]:
nspam_cv_fit = cv.fit(li_nspam)

In [146]:
result2 = nspam_cv_fit.transform(email).toarray()
result2

array([[1, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [147]:
## result1의 0이 아닌 갯수의 합, result2의 0이 아닌 갯수의 합

In [148]:
result1_count = 0
for count in result1[0]:
    if count != 0:
        result1_count += 1
result1_count

4

In [149]:
result2_count = 0
for count in result2[0]:
    if count != 0:
        result2_count += 1
result2_count

2

In [150]:
if result1_count >= result2_count :
    print("스팸메일 입니다!!!")
else:
    print("스팸메일이 아닙니다!!!")

스팸메일 입니다!!!
